### PR TITLE
Goal poset, judgement order, etc.

### PR DESCRIPTION
**Pull request by freebroccolo**
I added a few things but I don't know if this is how you would present it. Is the order for judgements how you were thinking of it? I'm wondering if it makes sense to say something about the result of applying `R` to `J1` and `J2` needing to have some condition as well (inclusion, etc.)

### CODE REVIEW

**Comment by jonsterling** [comment]
This looks really good, thanks.

Can you elaborate your thoughts on the condition on the result of applying `R` to `J1` and `J2`? I was also wondering whether something needed to be done about that...

**Comment by freebroccolo** [comment]
I'm not quite sure about the extra condition. Some examples might help. However, if you think of it topologically with tactics as being like opens and goals being like points then I would expect the ordering to be something like specialization where `J_2` is somehow "more defined". So every `R`-observation on `J_1` should have a corresponding `R`-observation on `J_2`, but there may be even more `R` observations on `J_2`. I guess that would mean `w_1` should be a subset of `w_2`. It's a little weird to think that the greater judgement should generate more goals though…

**Comment by jonsterling** [comment]
Interesting... I'm not too convinced about `w_1` being a subset of `w_2` yet, but maybe it will start to make sense to me later on. In any case, I suspect that what is needed will become a bit more clear when we prove the laws.

This PR looks good to me, so I'll merge it now.

**Comment by freebroccolo** [comment]
Yeah, I'm not too convinced by that explanation either. However, if we end up needing equivalence on judgements and we define it in terms of the order as `(J1 ≅ J2) ⇔ (J1 ≤ J2 ∧ J2 ≤ J1)` then it seems reasonable to expect `w_1 ⊇⊆ w_2` also.

**Comment by jonsterling** [comment]
I thought about it a little more and I wonder if we should flip around that order, and make it say something like the following:

> `J1 <~ J2` iff for all rules `R`, applicability of `R` to `J2` implies applicability of `R` to `J1`.

Intuitively, this can be read as "`J1` is easier to prove than `J2`" or something. It also makes the contravariance come out right when we try to talk about (pre)sheaves, I think (not that it matters, since variance is a purely formal matter).

Based on what we mean by "applicability", then, we would want this implication of applicabilities to also entail the fact that the derivation of `J1` could be computed from the derivation of `J2`. (I think). So we can read that statement formally as:

> `J1 <~ J2` iff for all rules `R`, `J1 !!- R => H1` implies `J2 !!- R => H2` such that `H1 subset* H2`.

Now, for `H1 subset* H2` judgement/relation, I wonder if it suffices to define it as mere subsethood. Maybe we want to define it inductive-inductively with `J1 <~ J2`, as something along the lines of "for all `J in H1`, there exists a `J2` in `H2` such that `J <~ J2`" or something. (The definitions are well-founded by induction on the length of the lists, etc.).

(Then, take the above definitions and complete them for the goals order).

What do you think? Have I got it backwards?

**Comment by jonsterling** [comment]
(Or, I think the arrows flip around again if we consider this `!!-` judgement as defining a presheaf into the category of derivations, as opposed to a presheaf into the category of lists of goals). I think that we have a number of choices that can be made here depending on how we want things to look.

**Comment by freebroccolo** [comment]
Hmm, I'll have to think about it a little more. It does seem like either way could work out but would change how some of the later results would be interpreted. As for the inductive-inductive approach, I think that would be fine. A bit more work but more concrete also.

**Pull request merged**
